services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.fastapi
    ports:
      - "8100:8000"

  streamlit:
    build:
      context: .
      dockerfile: docker/Dockerfile.streamlit
    ports:
      - "8600:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
